apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-auth
data:
  MYSQL_USERNAME: {{ .Values.MYSQL_USERNAME | b64enc }}
  MYSQL_PASSWORD: {{ .Values.MYSQL_PASSWORD | b64enc }}
  MYSQL_HOST: {{ .Values.MYSQL_HOST | b64enc }}
  MYSQL_PORT: {{ .Values.MYSQL_PORT | b64enc }}
  REDIS_ADDRESS: {{ .Values.REDIS_ADDRESS | b64enc }}
  REDIS_PASSWORD: {{ .Values.REDIS_PASSWORD | b64enc }}